services:
  - type: web
    name: jewish-md-session-site
    env: node
    rootDir: session-site
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
